=== GhassaneDz/gtm-projects/cm_PatientXML/patient2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.formation.org/patient2"
	xmlns:tns="http://www.formation.org/patient2" elementFormDefault="unqualified">
	<element name="patient" type="tns:Patient" />
	<complexType name="Patient">
		<!-- Let's define Patient with all his elements -->
		<sequence>
			<!-- Order matters -->
			<element name="id" type="int" />
			<element name="name" type="string" />
			<element name="age" type="int" />
			<element name="DOB" type="date" />
			<element name="email" type="string" />
			<element name="gender" type="string" />
			<element name="phone" type="string" />
		</sequence>
	</complexType>
</schema>

=== GhassaneDz/gtm-projects/cm_PatientXML/patient2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.formation.org/patient2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.formation.org/patient2 patient2.xsd ">
  <id>0</id>
  <name>name</name>
  <age>30</age>
  <DOB>2001-01-01</DOB>
  <email>email</email>
  <gender>gender</gender>
  <phone>phone</phone>
</tns:patient>
